/**
 * @file    Contact/ContactDataStructures.h
 * @brief   Data structures for reusable contact-control baselines.
 */

#ifndef CONTACT_DATA_STRUCTURES_H
#define CONTACT_DATA_STRUCTURES_H

#include <Eigen/Core>

namespace RobotLibrary { namespace Control {

/**
 * @brief Runtime contact state supplied by a front-end or higher-level controller.
 *
 * normalBase points in the direction where positive robot velocity increases
 * the normal contact force. For a board top surface, this is usually the inward
 * surface normal, not the outward wrench normal.
 */
struct ContactState
{
    Eigen::Vector3d normalBase = Eigen::Vector3d::UnitZ();
    Eigen::Vector3d surfaceVelocityBase = Eigen::Vector3d::Zero();
    double measuredNormalForce = 0.0;
    bool inContact = false;
};

/**
 * @brief Reference and tuning values for the baseline contact controller.
 */
struct ContactReference
{
    bool enabled = true;
    double targetNormalForce = 0.0;
    double forceResponseGain = 1500.0;   ///< Local normal stiffness model [N/m].
    double forceVelocityGain = 1.0;      ///< Converts force displacement error to velocity [1/s].
    double maxNormalVelocity = 0.04;     ///< Symmetric relative normal velocity limit [m/s].
    double forceDeadband = 0.0;          ///< Force-error deadband [N].
    bool approachWhenNotInContact = false;
    double approachVelocity = 0.0;       ///< Positive velocity along normalBase [m/s].
};

/**
 * @brief Contact command generated by a contact controller.
 */
struct ContactCommand
{
    Eigen::Vector3d normalVelocityBase = Eigen::Vector3d::Zero();
    double desiredRobotNormalVelocity = 0.0;
    double desiredRelativeNormalVelocity = 0.0;
    double forceError = 0.0;
    bool active = false;
    bool approachActive = false;
    bool releaseActive = false;
};

/**
 * @brief Diagnostics shared by contact-controller implementations.
 */
struct ContactDiagnostics
{
    double measuredNormalForce = 0.0;
    double targetNormalForce = 0.0;
    double forceError = 0.0;
    double surfaceNormalVelocity = 0.0;
    double desiredRelativeNormalVelocity = 0.0;
    double desiredRobotNormalVelocity = 0.0;
    double motionNormalVelocityBeforeMerge = 0.0;
    double motionNormalVelocityAfterMerge = 0.0;
    bool active = false;
    bool approachActive = false;
    bool releaseActive = false;
    bool normalValid = false;
};

} } // namespace

#endif
